### ISSUE TITLE
GSoC 2020 Task List

### ISSUE THREAD

**Issue by sdhoundiyal** [sdhoundiyal/MapMint4ME#1]
- [ ] Test for the understanding of Github (Version Control)
       Fork the MapMint4ME Github repository and create a task list in the issues section of the repository.

- [ ] Test for the understanding of Android Studio and MapMint4ME coding style
        Setup Android Studio for development.
        Build the MapMint4ME application on Android Studio.
- [ ] Test for the understanding of Augmented Reality Development
        Implement a basic AR feature in the MapMint4ME Android application. It could be an implementation of AR functionality (based on ARCore) on a button click from the MapMint4ME application.
